### ISSUE TITLE
Unable to create VNFs on Openstack deployment

### ISSUE THREAD

**Issue by michaelspedersen** [cncf/cnf-testbed#250]
Openstack deployment based on [fsharp-freeze-chef-recipes-ver branch](https://github.com/cncf/cnf-testbed/tree/fsharp-freeze-chef-recipes-ver).

Prerequisites (VLANs/Networks, flavors etc.) are created using scripts available in `/root/` on the controller. (partially based on [Documentation](https://github.com/cncf/cnf-testbed/blob/master/docs/openstack_deploy.md#testing))

`create_masq.sh` seems to be successful, but an error with `iptables` can be seen in the output:
```
* Applying /etc/sysctl.d/99-sysctl.conf ...
net.core.rmem_default = 12582912
net.core.wmem_default = 12582912
net.core.rmem_max = 12582912
net.core.wmem_max = 12582912
net.ipv4.tcp_rmem = 10240 87380 12582912
net.ipv4.tcp_wmem = 10240 87380 12582912
net.ipv4.tcp_congestion_control = westwood
net.ipv4.ip_forward = 1
net.ipv6.conf.default.forwarding = 1
* Applying /etc/sysctl.conf ...
net.core.rmem_default = 12582912
net.core.wmem_default = 12582912
net.core.rmem_max = 12582912
net.core.wmem_max = 12582912
net.ipv4.tcp_rmem = 10240 87380 12582912
net.ipv4.tcp_wmem = 10240 87380 12582912
net.ipv4.tcp_congestion_control = westwood
net.ipv4.ip_forward = 1
net.ipv6.conf.default.forwarding = 1
iptables: No chain/target/match by that name.
```

```
$ openstack network list
+--------------------------------------+----------+--------------------------------------+
| ID                                   | Name     | Subnets                              |
+--------------------------------------+----------+--------------------------------------+
| 041bf999-ae28-4db2-8a88-6b979b0a9621 | middle1  | a622955e-ff16-4bcf-88e3-e1b2875463dc |
| 1a2d20cc-94be-4d59-8b12-4e9b93a9db22 | middle2  | d3ebaf3d-96df-48d1-98bb-e8183a1c54a6 |
| 38d0b995-76c0-4356-b435-dfd670753805 | vlan1088 | a36c1523-d5d7-4315-a4d7-9f7b674adc7f |
| 5c1703a3-4621-44a9-a47e-37f8a75a8519 | netext   | b25e9679-1546-4186-9a9b-7e7e81a77567 |
| f52b0fe4-a56d-4cb4-b1a4-bb2f46ac7709 | vlan1087 | e556345a-e4ef-432d-8d1d-b81861e61297 |
+--------------------------------------+----------+--------------------------------------+
```

```
$ openstack flavor list
+----+----------+------+------+-----------+-------+-----------+
| ID | Name     |  RAM | Disk | Ephemeral | VCPUs | Is Public |
+----+----------+------+------+-----------+-------+-----------+
| 1  | c0.small | 8192 |   10 |         0 |     1 | True      |
| 10 | vnf.3c   | 8192 |   10 |         0 |     3 | True      |
| 2  | c1.small | 8192 |   10 |         0 |     1 | True      |
+----+----------+------+------+-----------+-------+-----------+
```

Image is built using [install-prereqs.sh](https://github.com/cncf/cnf-testbed/blob/master/comparison/kubecon18-chained_nf_test/VNF_openstack/vm_image/diskimage-builder/install-prereqs.sh) followed by [build_vm.sh](https://github.com/cncf/cnf-testbed/blob/master/comparison/kubecon18-chained_nf_test/VNF_openstack/vm_image/diskimage-builder/build_vm.sh)

```
$ openstack image list
+--------------------------------------+----------+--------+
| ID                                   | Name     | Status |
+--------------------------------------+----------+--------+
| e1847f1a-01d2-4957-a067-b56085bf3781 | cirros   | active |
| bb7029db-56fb-41cd-97e0-19c3b043fcd3 | vnf_base | active |
| f86dbb0d-2a38-44e4-852c-38ed8d23b367 | xenial   | active |
+--------------------------------------+----------+--------+
```

SSH key created (based on `create_instance.sh` script in `/root/`):
```
ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa
openstack keypair create oskey --public-key ~/.ssh/id_rsa.pub
```

VNF(s) created using [create_vnfs.sh](https://github.com/cncf/cnf-testbed/blob/master/comparison/kubecon18-chained_nf_test/VNF_openstack/create_vnfs.sh), after setting necessary environment variables:
```
export VLANID_LEFT=1087
export VLANID_RIGHT=1088
export TREX_MAC1=ee:00:51:d3:06:e8
export TREX_MAC2=ba:a7:6c:aa:67:7b
export TEMPDIR=/tmp/

# One chain with one node
./create_vnfs.sh 1 1
```

VNFs get stuck in "BUILD" state, and after reaching timeout fails with `Failed to allocate the network(s)`

```
$ openstack server list
+--------------------------------------+-------+--------+-----------------------------------------------------------------+----------+--------+
| ID                                   | Name  | Status | Networks                                                        | Image    | Flavor |
+--------------------------------------+-------+--------+-----------------------------------------------------------------+----------+--------+
| 39b0fe2a-6246-4aca-91b5-e698e98982e0 | 1_1_1 | BUILD  | vlan1087=10.26.0.7, 10.26.0.16, 10.20.30.7; vlan1088=10.152.0.3 | vnf_base | vnf.3c |
+--------------------------------------+-------+--------+-----------------------------------------------------------------+----------+--------+

# After timeout:
$ openstack server list
+--------------------------------------+-------+--------+----------+----------+--------+
| ID                                   | Name  | Status | Networks | Image    | Flavor |
+--------------------------------------+-------+--------+----------+----------+--------+
| 39b0fe2a-6246-4aca-91b5-e698e98982e0 | 1_1_1 | ERROR  |          | vnf_base | vnf.3c |
+--------------------------------------+-------+--------+----------+----------+--------+
```

On the compute node, VPP shows vhost interfaces while the VNF is in "BUILD" state:
```
$ vppctl show int
              Name               Idx    State  MTU (L3/IP4/IP6/MPLS)     Counter          Count
TwentyFiveGigabitEthernet5e/0/0   1     down         9000/0/0/0
TwentyFiveGigabitEthernet5e/0/1   2      up          9000/0/0/0     rx packets                    78
                                                                    rx bytes                   33540
                                                                    drops                         78
TwentyFiveGigabitEthernet5e/0/1.  5      up           0/0/0/0
TwentyFiveGigabitEthernet5e/0/1.  6      up           0/0/0/0
VirtualEthernet0/0/0              7      up          9000/0/0/0
VirtualEthernet0/0/1              8      up          9000/0/0/0
VirtualEthernet0/0/2              9      up          9000/0/0/0
local0                            0     down          0/0/0/0
tapcli-0                          3     down         9000/0/0/0     drops                       6561
tapcli-1                          4     down         9000/0/0/0     drops                       6560
```

Running `vppctl show vhost-user` shows that vhosts are not connected to VPP running in the VNF.

After reaching "ERROR" state interfaces are removed from VPP.

Looking at VPP logs (`/var/log/vpp`), `vpp.log` is not showing anything useful, while `vpp-agent.log` shows the following:
```
2019/ 8/21 08:25:45:223: ***** Start: PID 3747 *****
2019/ 8/21 08:26:04:951: ***** Start: PID 4050 *****
2019/ 8/21 08:26:05:663: ***** Start: PID 4062 *****
2019/ 8/21 08:26:06:151: ***** Start: PID 4069 *****
2019/ 8/21 08:26:06:659: ***** Start: PID 4075 *****
2019/ 8/21 08:26:07:159: ***** Start: PID 4081 *****
2019/ 8/21 08:28:07:083: ***** Start: PID 5241 *****
2019/ 8/21 08:28:09:263: ***** Startup Config *****
tap connect uplink
tap connect vxlan
2019/ 8/21 08:28:09:263: ***** End Startup Config *****
2019/ 8/21 08:50:00:081[0]: show int2019/ 8/21 08:54:13:408[0]: show int2019/ 8/23 14:01:56:376[0]: show int2019/ 8/23 14:02:00:504[0]: show memif2019/ 8/23 14:02:02:552[0]: show vhost2019/ 8/23 14:33:57:483[0]: show int2019/ 8/23 14:35:20:803[0]: show int2019/ 8/23 14:36:43:703[0]: show vhost-user root@michael-os-comp1:/var/log/vpp# ls
vpp-agent.log  vpp.log
root@michael-os-comp1:/var/log/vpp# cat /etc/vpp/^C
root@michael-os-comp1:/var/log/vpp# cat vpp-agent.log
2019-08-21 08:28:10.344 5309 WARNING networking_vpp.etcdutils [-] etcd is not using HTTPS, insecure setting
2019-08-21 08:43:16.308 5309 ERROR etcd.client [-] Request to server http://139.178.70.170:2379 failed: ProtocolError('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read)): ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
2019-08-21 08:43:16.308 5309 INFO etcd.client [-] Reconnection allowed, looking for another server.
2019-08-21 08:43:16.308 5309 INFO etcd.client [-] Selected new etcd server http://139.178.70.166:2379
2019-08-21 08:44:15.457 5309 ERROR etcd.client [-] Unexpected request failure, re-raising.: Timeout: 65 seconds (silent)
2019-08-21 08:44:15.457 5309 ERROR etcd.client Traceback (most recent call last):
2019-08-21 08:44:15.457 5309 ERROR etcd.client   File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 863, in wrapper
2019-08-21 08:44:15.457 5309 ERROR etcd.client     _ = response.data
2019-08-21 08:44:15.457 5309 ERROR etcd.client   File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 188, in data
2019-08-21 08:44:15.457 5309 ERROR etcd.client     return self.read(cache_content=True)
2019-08-21 08:44:15.457 5309 ERROR etcd.client   File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 380, in read
2019-08-21 08:44:15.457 5309 ERROR etcd.client     data = self._fp.read()
2019-08-21 08:44:15.457 5309 ERROR etcd.client   File "/usr/lib/python2.7/httplib.py", line 573, in read
2019-08-21 08:44:15.457 5309 ERROR etcd.client     return self._read_chunked(amt)
2019-08-21 08:44:15.457 5309 ERROR etcd.client   File "/usr/lib/python2.7/httplib.py", line 615, in _read_chunked
2019-08-21 08:44:15.457 5309 ERROR etcd.client     line = self.fp.readline(_MAXLINE + 1)
2019-08-21 08:44:15.457 5309 ERROR etcd.client   File "/usr/lib/python2.7/socket.py", line 480, in readline
2019-08-21 08:44:15.457 5309 ERROR etcd.client     data = self._sock.recv(self._rbufsize)
2019-08-21 08:44:15.457 5309 ERROR etcd.client   File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 363, in recv
2019-08-21 08:44:15.457 5309 ERROR etcd.client     return self._recv_loop(self.fd.recv, b'', bufsize, flags)
2019-08-21 08:44:15.457 5309 ERROR etcd.client   File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 357, in _recv_loop
2019-08-21 08:44:15.457 5309 ERROR etcd.client     self._read_trampoline()
2019-08-21 08:44:15.457 5309 ERROR etcd.client   File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 328, in _read_trampoline
2019-08-21 08:44:15.457 5309 ERROR etcd.client     timeout_exc=socket_timeout('timed out'))
2019-08-21 08:44:15.457 5309 ERROR etcd.client   File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 207, in _trampoline
2019-08-21 08:44:15.457 5309 ERROR etcd.client     mark_as_closed=self._mark_as_closed)
2019-08-21 08:44:15.457 5309 ERROR etcd.client   File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/__init__.py", line 163,
in trampoline
2019-08-21 08:44:15.457 5309 ERROR etcd.client     return hub.switch()
2019-08-21 08:44:15.457 5309 ERROR etcd.client   File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 295, in switch
2019-08-21 08:44:15.457 5309 ERROR etcd.client     return self.greenlet.switch()
2019-08-21 08:44:15.457 5309 ERROR etcd.client Timeout: 65 seconds (silent)
2019-08-21 08:44:15.457 5309 ERROR etcd.client
2019-08-23 13:58:37.762 5309 INFO networking_vpp.agent.server [-] Set subinterface vlan tag pop response: l2_interface_vlan_tag_rewrite_reply(_0=148, context=12, retval=0)
2019-08-23 13:58:37.811 5309 INFO networking_vpp.agent.server [-] Set subinterface vlan tag pop response: l2_interface_vlan_tag_rewrite_reply(_0=148, context=22, retval=0)
2019-08-23 13:58:37.816 5309 INFO networking_vpp.agent.server [-] Set subinterface vlan tag pop response: l2_interface_vlan_tag_rewrite_reply(_0=148, context=32, retval=0)
2019-08-23 13:58:37.818 5309 INFO networking_vpp.agent.server [-] Set subinterface vlan tag pop response: l2_interface_vlan_tag_rewrite_reply(_0=148, context=42, retval=0)
2019-08-23 13:58:38.366 5309 INFO networking_vpp.agent.server [-] Set subinterface vlan tag pop response: l2_interface_vlan_tag_rewrite_reply(_0=148, context=49, retval=0)
2019-08-23 13:58:38.977 5309 INFO networking_vpp.utils.file_monitor [-] File: c77ba608-2be6-464a-8972-07560cf4da88 CREATE event processed
2019-08-23 13:58:41.359 5309 INFO networking_vpp.utils.file_monitor [-] File: eb9f1545-ed3d-4abe-aa2c-bc937d6aa237 CREATE event processed
2019-08-23 13:58:44.353 5309 INFO networking_vpp.utils.file_monitor [-] File: 953f7f4f-d7b3-4632-94ca-6ab17a93910c CREATE event processed
2019-08-23 14:03:48.918 5309 INFO networking_vpp.utils.file_monitor [-] File c77ba608-2be6-464a-8972-07560cf4da88 removed from tracked file index
2019-08-23 14:03:48.919 5309 INFO networking_vpp.utils.file_monitor [-] File eb9f1545-ed3d-4abe-aa2c-bc937d6aa237 removed from tracked file index
2019-08-23 14:03:48.919 5309 INFO networking_vpp.utils.file_monitor [-] File 953f7f4f-d7b3-4632-94ca-6ab17a93910c removed from tracked file index
```

The connection to `etcd` seems to fail, but I am not sure if this is the cause of what is observed here. 

I tried using the `create_instance.sh` script located in `/root/` to create a simpler VNF, but similar openstack output is returned ("ERROR" state)

**Comment by michaelspedersen** [comment]
With the fix mentioned above, I am able to run VNFs, and I can see traffic passing through it as well. Once added to master I believe the ticket can be closed

**Comment by linkous8** [comment]
Made a small update so the aenum package is installed on Intel deployments as it is still required there. Tested on Mellanox and verified the aenum package is not installed there

https://github.com/cncf/cnf-testbed/pull/254
